#!/bin/bash
sudo yum update -y
sudo yum install -y java-1.8.0-openjdk screen git -y
sudo yum remove java-1.7.0-openjdk -y
git clone https://github.com/cyroth/minecraft-server-setup-aws.git /home/ec2-user/minecraft-server-setup-aws
chown -R ec2-user.ec2-user /home/ec2-user/minecraft-server-setup-aws
